import type { Employee } from "@/types/employee";
import type { SettingItem } from "@/types/settings";

// Demo-only adapter. Production replaces this module with repository reads.
export const seedEmployees: Employee[] = [
  {
    id: "1",
    employeeNumber: "WH-2024-001",
    name: "Amelia Santos",
    position: "Project Coordinator",
    projectSite: "Metro North",
    dateHired: "2024-01-08",
    endOfContract: "2026-12-31",
    employmentStatus: "Regular",
    contactNumber: "+63 917 555 0124",
    address: "Quezon City, Metro Manila",
    sssNumber: "demo",
    philHealthNumber: "demo",
    pagIbigNumber: "demo",
    tinNumber: "demo",
    leaveCredits: { sickLeave: 8, vacationLeave: 12 },
  },
  {
    id: "2",
    employeeNumber: "WH-2023-018",
    name: "Marcus Villanueva",
    position: "Site Supervisor",
    projectSite: "Harbor Point",
    dateHired: "2023-08-14",
    endOfContract: "2026-08-13",
    employmentStatus: "Regular",
    contactNumber: "+63 905 312 7781",
    address: "Pasig City, Metro Manila",
    sssNumber: "demo",
    philHealthNumber: "demo",
    pagIbigNumber: "demo",
    tinNumber: "demo",
    leaveCredits: { sickLeave: 6, vacationLeave: 9 },
  },
  {
    id: "3",
    employeeNumber: "WH-2024-007",
    name: "Leah Dela Cruz",
    position: "Safety Officer",
    projectSite: "Metro North",
    dateHired: "2024-03-22",
    endOfContract: "2027-03-21",
    employmentStatus: "AWOL",
    contactNumber: "+63 918 220 4455",
    address: "Makati City, Metro Manila",
    sssNumber: "demo",
    philHealthNumber: "demo",
    pagIbigNumber: "demo",
    tinNumber: "demo",
    leaveCredits: { sickLeave: 10, vacationLeave: 14 },
  },
  {
    id: "4",
    employeeNumber: "WH-2022-042",
    name: "Rafael Garcia",
    position: "Field Engineer",
    projectSite: "Skyline Residences",
    dateHired: "2022-11-03",
    endOfContract: "2025-11-02",
    employmentStatus: "Contractual",
    contactNumber: "+63 917 804 1102",
    address: "Cebu City, Cebu",
    sssNumber: "demo",
    philHealthNumber: "demo",
    pagIbigNumber: "demo",
    tinNumber: "demo",
    leaveCredits: { sickLeave: 4, vacationLeave: 7 },
  },
];

export const seedSettings: SettingItem[] = [
  {
    id: "position-1",
    name: "Project Coordinator",
    kind: "position",
    active: true,
  },
  { id: "position-2", name: "Site Supervisor", kind: "position", active: true },
  { id: "position-3", name: "Safety Officer", kind: "position", active: true },
  { id: "position-4", name: "Field Engineer", kind: "position", active: true },
  { id: "project-1", name: "Metro North", kind: "project", active: true },
  { id: "project-2", name: "Harbor Point", kind: "project", active: true },
  {
    id: "project-3",
    name: "Skyline Residences",
    kind: "project",
    active: true,
  },
  { id: "project-4", name: "Head Office", kind: "project", active: true },
  { id: "status-1", name: "Contractual", kind: "status", active: true },
  { id: "status-2", name: "Probationary", kind: "status", active: true },
  { id: "status-3", name: "Regular", kind: "status", active: true },
  { id: "status-4", name: "Terminated", kind: "status", active: true },
  { id: "status-5", name: "Resigned", kind: "status", active: true },
  { id: "status-6", name: "AWOL", kind: "status", active: true },
];
